Supermarket cmd with install, download and search support
chef/go-chef-cli pull request #1
Opened 2022-02-16 08:08 UTC by sanghinitin

First PR

2022-02-21 20:19 UTC, i5pranay93 approved these changes

2022-02-22 18:03 UTC, marcparadise requested changes
The direction looks good, but I do have some concerns: 

* You should make use of go-chef, https://github.com/chef/go-chef. This contains an API client with pretty extensive (possibly complete) coverage of the Chef Server API. It includes many things that have been implemented here, including client, auth, requests, cookbook metadata structure and access, etc.  *edit*: Or is the 'client' here for supermarket only? If so, that should be reflected in the naming.
* I see a lot of internal package components outputting directly to the UI.  This should be done only at `cmd` level - internal packages should not have knowledge of UI at all; instead they should provde error responses to the caller (in the cmd package) and allow the caller to display and format. 
* Is there any design doc describing the structure of go-knife, and how it fits into the client-side ecosystem?

2022-02-22 18:03 UTC, marcparadise commented on README.md
> +Copyright 2008-2022, Chef Software, Inc.
This copyright is wrong

2022-02-22 18:03 UTC, marcparadise commented on cmd/supermarketDownload.go
> +type cookbookData struct {
This struct should probably be defined in the `supermarket` package. I don't think it's used here, and isn't a concern of the top-level CLI command.

2022-02-22 18:03 UTC, marcparadise commented on cmd/supermarketInstall.go
> +	Short: "Search indexes allow queries to be made for any type of data that is indexed by the Chef Infra Server, including data bags (and data bag items), environments, nodes, and roles",
The text here and below does not seem right for `supermarket install`

2022-02-22 18:03 UTC, marcparadise commented on cmd/supermarketSearch.go
> +	Short: "Search indexes allow queries to be made for any type of data that is indexed by the Chef Infra Server, including data bags (and data bag items), environments, nodes, and roles",
Same with the text being off

2022-02-22 18:03 UTC, marcparadise commented on core/git.go
> +func IsGitRepoExists(path string) bool {
`DoesGitRepoExist`

2022-02-22 18:03 UTC, marcparadise commented on core/git.go
> +func isDirExists(path string) bool {
`doesDirExist`

2022-02-22 18:03 UTC, marcparadise commented on core/presenterIface.go
> +	DisplayCookBook(data interface{}) interface{}
`DisplayCookbook` seems out of place here. Without seeing implementation, it's hard to say - but this is very specific compared to the more general methods above.  I also don't see this function referenced in this PR.

2022-02-22 18:03 UTC, marcparadise commented on cmd/supermarketDownload.go
> +			ui.Error(err.Error())
Is this error going to be suitable for display - that is, meaningful and actionable by the user?

2022-02-22 18:03 UTC, marcparadise commented on supermarket/cookbookDownload.go
> +		ui.Msg(ui.ColorMsg("DEPRECATION: This cookbook has been deprecated. ", "yellow"))
In general we have been trying to avoid having components outside of the cmd package communicating with the user. Any errors should be returned to the caller for proper formatting and output. This ensures that the the non-UI packages don't have to concern themselves with displaying text to the user and makes it easier to enforce consistent behavior in communicating with the user.

2022-02-22 18:03 UTC, marcparadise commented on dsl/metadata.go
> +package dsl
Is this cookbook metadata, or metadata specific to supermarket content?

2022-03-10 14:08 UTC, nikhil2611 approved these changes

2022-03-10 14:08 UTC, merged